<?php

/**
 * TermTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TermTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TermTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Term');
    }
}